leo_homepage:
    path:     /
    defaults: { _controller: LeoBundle:Default:index }

leo_reunion:
    resource: "@LeoBundle/Resources/config/routing/reunion.yml"
    prefix:   /reunion

leo_stock:
    resource: "@LeoBundle/Resources/config/routing/stock.yml"
    prefix:   /stock